### ISSUE TITLE
Error  while using the package

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [diepnghitinh/christian_picker_image#15]
Hi,  
Im trying to use this package and as soon as it opens the window to select the images it crashes with following message.

```
I/flutter ( 9889): takeImage
W/ActivityThread( 9889): handleWindowVisibility: no activity for token android.os.BinderProxy@4a23e6c
E/ensugar.patien( 9889): Invalid ID 0x00000000.
W/ensugar.patien( 9889): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ensugar.patien( 9889): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
V/FlingOptimizerScroller( 9889): FlingOptimizerOverScroller Init
V/ViewRootImpl( 9889): The specified message queue synchronization  barrier token has not been posted or has already been removed
D/DecorView( 9889): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@9c88f3a[ImagePickerActivity]
E/RecyclerView( 9889): No adapter attached; skipping layout
W/Choreographer( 9889): Already have a pending vsync event.  There should only be one at a time.
W/Glide   ( 9889): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/AndroidRuntime( 9889): Shutting down VM
E/AndroidRuntime( 9889): FATAL EXCEPTION: main
E/AndroidRuntime( 9889): Process: com.sensai.sevensugar.patient, PID: 9889
E/AndroidRuntime( 9889): java.lang.NoSuchMethodError: No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.sensai.sevensugar.patient-0Blpt-iM_cM0631QWEIgIA==/base.apk!classes32.dex)
E/AndroidRuntime( 9889): 	at com.imagepicker.features.imageloader.DefaultImageLoader.loadImage(DefaultImageLoader.java:17)
E/AndroidRuntime( 9889): 	at com.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:55)
E/AndroidRuntime( 9889): 	at com.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:24)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
E/AndroidRuntime( 9889): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
E/AndroidRuntime( 9889): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
E/AndroidRuntime( 9889): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 9889): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 9889): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:786)
E/AndroidRuntime( 9889): 	at android.view.View.layout(View.java:22085)
E/AndroidRuntime( 9889): 	at android.view.ViewGroup.layout(ViewGroup.java:6290)
E/AndroidRuntime( 9889): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3333)
E/AndroidRuntime( 9889): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2810)
E/AndroidRuntime( 9889): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
E/AndroidRuntime( 9889): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8018)
E/AndroidRuntime( 9889): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
E/AndroidRuntime( 9889): 	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
E/AndroidRuntime( 9889): 	at android.view.Choreographer.doFrame(Choreographer.java:902)
E/AndroidRuntime( 9889): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
E/AndroidRuntime( 9889): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 9889): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 9889): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 9889): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime( 9889): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9889): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 9889): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process ( 9889): Sending signal. PID: 9889 SIG: 9
Lost connection to device.

```

**Comment by LaxmikanthMadhyastha** [comment]
Sorry issue is found to be something else and not with the package
